### ISSUE TITLE
Is it possible to add support for the new 2022 API?

### ISSUE THREAD

**Issue by Cuprani** [ricott/homey-com.volvocars#21]
In september 2022 Volvo has released the API for the 2022 + (google) cars.
It would be amazing fantastic if you could add (or make another app) for de 2022+ Volvo's.

Also see https://developer.volvocars.com/apis/energy/specification/[https://developer.volvocars.com/apis/energy/specification/](https://developer.volvocars.com/apis/energy/specification/) 

from the site:
_This API works for all plug-in hybrid and electric vehicles which are equipped with Google Automotive System (Google built-in). Recharge status data is updated both when the vehicle is parked (key-off) and when a charging session is initiated._

/Nils

**Comment by ricott** [comment]
Thanks, I have seen the API endpoints. Allows only for reading energy data, with no control of the car for doing anything.
Will see when I get bored if I'm able to get something running. You need to get approval from Volvo to be able to use this API in an app, so that is another step as well.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/31240726/224933044-6ad79ffd-ff8c-444f-a6b5-d479caa2df6b.png">

**Comment by Cuprani** [comment]
Reading the data is better then nothing :-) Would be great to use some of that information on my home dashboard.
I wish I was able to help or create something like that myself, but sadly I don't have the knowledge for it. Hope you get bored soon ;-)

**Comment by Deejaybaze** [comment]
Hi. I could see on the developer site that it has been updated. Is there a plan for update on this app?

**Comment by ricott** [comment]
What has been updated?

**Comment by ricott** [comment]
https://community.homey.app/t/app-pro-volvo-on-call/20828/98?u=richard_b
