### ISSUE TITLE
 average fuel consumption

### ISSUE THREAD

**Issue by rmsappl** [ricott/homey-com.volvocars#7]
I would like to Log average fuel consumption after Engine stopped

**Comment by ricott** [comment]
We have an "Engine stopped" trigger, I guess we could add a token to that event. There is also a field in the status API called "averageFuelConsumption". I'm however guessing this is not a value per trip, but rather shows average between manual resets. The value we get seems to be cl / 10km. I have access to two cars and they show 70 vs 28 (phev).

**Comment by rmsappl** [comment]
How do I use averageFuelConsumption in a flow #homey?

**Comment by ricott** [comment]
Today you cant obviously since it is not there. My proposal was to add it as a token in the existing trigger called Engine stopped. The "When" card in a flow. Then in your "And" and "Then" cards you can reference the token. Something like the below.
![image](https://user-images.githubusercontent.com/31240726/83193452-59cb7280-a137-11ea-8d4a-9c825e090703.png)

**Comment by rmsappl** [comment]
that would be great!!

**Comment by ricott** [comment]
Available in version 1.1.2 that is waiting for approval by Athom.
